I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 65, in script
    with dissole
  File "game/script.rpy", line 65, in <module>
    with dissole
NameError: name 'dissole' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 65, in script
    with dissole
  File "/Users/abeiltedla/Desktop/renpy-8.2.1-sdk/renpy/ast.py", line 1356, in execute
    trans = renpy.python.py_eval(self.expr)
  File "/Users/abeiltedla/Desktop/renpy-8.2.1-sdk/renpy/python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Users/abeiltedla/Desktop/renpy-8.2.1-sdk/renpy/python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 65, in <module>
    with dissole
NameError: name 'dissole' is not defined

macOS-10.15.6-x86_64-i386-64bit x86_64
Ren'Py 8.2.1.24030407
Just Another Day 1.0
Sat Apr 27 19:52:17 2024
